repos:
- repo: local
  hooks:
    - id: black
      name: black formatter
      entry: make format
      language: system
      pass_filenames: false
      args: []
- repo: local
  hooks:
    - id: pytest
      name: run unit test
      entry: pytest
      language: system
      pass_filenames: false
      args: []