version: "3.9"
services:
  web:
    build: .
    ports:
      - "8005:8005"
    # command: python3 server.py
    volumes:
      - .:/app
    container_name: portfolio
    image: huzzy619/portfolio:0.1
    env_file:
      - .env
