# Generated by Django 4.1.2 on 2022-10-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dossier", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=550)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("budget_level", models.CharField(max_length=250)),
                ("requirements", models.TextField()),
                ("created_on", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("kind", models.CharField(max_length=250)),
                ("image", models.ImageField(upload_to="works")),
                ("link", models.URLField()),
            ],
        ),
    ]
