# Generated by Django 4.1.2 on 2022-10-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dossier", "0002_contact_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="-", upload_to="profile"),
            preserve_default=False,
        ),
    ]
