# Generated by Django 4.1.2 on 2022-10-13 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dossier", "0004_skill"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="contact",
            name="last_name",
            field=models.CharField(default="-", max_length=550),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contact",
            name="budget_level",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="skill",
            name="proficiency",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
