# Generated by Django 4.1.4 on 2023-02-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier', '0006_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
