# Generated by Django 4.2.1 on 2023-05-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier', '0008_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(),
        ),
    ]
