# Generated by Django 4.2.1 on 2023-05-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier', '0010_project_date_created_project_date_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creator',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
